export interface Word {
  id: string
  hanzi: string
  pinyin: string
  hskLevel: number
  meaningEn: string
  meaningMn: string
  audioUrl: string
}

export const words: Word[] = [
  {
    id: "nihao",
    hanzi: "你好",
    pinyin: "nǐ hǎo",
    hskLevel: 1,
    meaningEn: "Hello",
    meaningMn: "Сайн байна уу",
    audioUrl: "/audio/nihao.mp3",
  },
  {
    id: "shuxue",
    hanzi: "数学",
    pinyin: "shù xué",
    hskLevel: 2,
    meaningEn: "Mathematics",
    meaningMn: "Математик",
    audioUrl: "/audio/shuxue.mp3",
  },
  {
    id: "xuexiao",
    hanzi: "学校",
    pinyin: "xué xiào",
    hskLevel: 1,
    meaningEn: "School",
    meaningMn: "Сургууль",
    audioUrl: "/audio/xuexiao.mp3",
  },
  {
    id: "meiguoren",
    hanzi: "美国人",
    pinyin: "měi guó rén",
    hskLevel: 2,
    meaningEn: "American",
    meaningMn: "Америкчуу",
    audioUrl: "/audio/meiguoren.mp3",
  },
  {
    id: "mum",
    hanzi: "妈妈",
    pinyin: "mā ma",
    hskLevel: 1,
    meaningEn: "Mother",
    meaningMn: "Ээж",
    audioUrl: "/audio/mama.mp3",
  },
  {
    id: "baba",
    hanzi: "爸爸",
    pinyin: "bà ba",
    hskLevel: 1,
    meaningEn: "Father",
    meaningMn: "Аав",
    audioUrl: "/audio/baba.mp3",
  },
  {
    id: "jiejie",
    hanzi: "姐姐",
    pinyin: "jiě jie",
    hskLevel: 1,
    meaningEn: "Older Sister",
    meaningMn: "Дүү",
    audioUrl: "/audio/jiejie.mp3",
  },
  {
    id: "didi",
    hanzi: "弟弟",
    pinyin: "dì di",
    hskLevel: 1,
    meaningEn: "Younger Brother",
    meaningMn: "Дүү",
    audioUrl: "/audio/didi.mp3",
  },
  {
    id: "shuimeng",
    hanzi: "睡眠",
    pinyin: "shuì mián",
    hskLevel: 3,
    meaningEn: "Sleep",
    meaningMn: "Унтах",
    audioUrl: "/audio/shuimeng.mp3",
  },
  {
    id: "huoche",
    hanzi: "火车",
    pinyin: "huǒ chē",
    hskLevel: 2,
    meaningEn: "Train",
    meaningMn: "Галт тэрэг",
    audioUrl: "/audio/huoche.mp3",
  },
  {
    id: "shui",
    hanzi: "水",
    pinyin: "shuǐ",
    hskLevel: 1,
    meaningEn: "Water",
    meaningMn: "Ус",
    audioUrl: "/audio/shui.mp3",
  },
  {
    id: "fan",
    hanzi: "饭",
    pinyin: "fàn",
    hskLevel: 1,
    meaningEn: "Rice / Meal",
    meaningMn: "Будаа / Хоол",
    audioUrl: "/audio/fan.mp3",
  },
  {
    id: "shuiguo",
    hanzi: "水果",
    pinyin: "shuǐ guǒ",
    hskLevel: 1,
    meaningEn: "Fruit",
    meaningMn: "Жимс",
    audioUrl: "/audio/shuiguo.mp3",
  },
  {
    id: "pingguo",
    hanzi: "苹果",
    pinyin: "píng guǒ",
    hskLevel: 1,
    meaningEn: "Apple",
    meaningMn: "Алим",
    audioUrl: "/audio/pingguo.mp3",
  },
  {
    id: "niunai",
    hanzi: "牛奶",
    pinyin: "niú nǎi",
    hskLevel: 1,
    meaningEn: "Milk",
    meaningMn: "Сүү",
    audioUrl: "/audio/niunai.mp3",
  },
  {
    id: "cha",
    hanzi: "茶",
    pinyin: "chá",
    hskLevel: 1,
    meaningEn: "Tea",
    meaningMn: "Цай",
    audioUrl: "/audio/cha.mp3",
  },
  {
    id: "jiaozi",
    hanzi: "饺子",
    pinyin: "jiǎo zi",
    hskLevel: 2,
    meaningEn: "Dumpling",
    meaningMn: "Бууз",
    audioUrl: "/audio/jiaozi.mp3",
  },
  {
    id: "mifan",
    hanzi: "米饭",
    pinyin: "mǐ fàn",
    hskLevel: 1,
    meaningEn: "Cooked Rice",
    meaningMn: "Будаа",
    audioUrl: "/audio/mifan.mp3",
  },
  {
    id: "rou",
    hanzi: "肉",
    pinyin: "ròu",
    hskLevel: 1,
    meaningEn: "Meat",
    meaningMn: "Мах",
    audioUrl: "/audio/rou.mp3",
  },
  {
    id: "yu",
    hanzi: "鱼",
    pinyin: "yú",
    hskLevel: 1,
    meaningEn: "Fish",
    meaningMn: "Загас",
    audioUrl: "/audio/yu.mp3",
  },
  {
    id: "jidan",
    hanzi: "鸡蛋",
    pinyin: "jī dàn",
    hskLevel: 1,
    meaningEn: "Egg",
    meaningMn: "Өндөг",
    audioUrl: "/audio/jidan.mp3",
  },
  {
    id: "shucai",
    hanzi: "蔬菜",
    pinyin: "shū cài",
    hskLevel: 2,
    meaningEn: "Vegetable",
    meaningMn: "Хүнсний ногоо",
    audioUrl: "/audio/shucai.mp3",
  },
  {
    id: "xihongshi",
    hanzi: "西红柿",
    pinyin: "xī hóng shì",
    hskLevel: 2,
    meaningEn: "Tomato",
    meaningMn: "Улаан лооль",
    audioUrl: "/audio/xihongshi.mp3",
  },
  {
    id: "qiezi",
    hanzi: "茄子",
    pinyin: "qié zi",
    hskLevel: 2,
    meaningEn: "Eggplant",
    meaningMn: "Бадриаан",
    audioUrl: "/audio/qiezi.mp3",
  },
  {
    id: "tudou",
    hanzi: "土豆",
    pinyin: "tǔ dòu",
    hskLevel: 2,
    meaningEn: "Potato",
    meaningMn: "Төмс",
    audioUrl: "/audio/tudou.mp3",
  },
  {
    id: "yifu",
    hanzi: "衣服",
    pinyin: "yī fu",
    hskLevel: 1,
    meaningEn: "Clothes",
    meaningMn: "Хувцас",
    audioUrl: "/audio/yifu.mp3",
  },
  {
    id: "kuzi",
    hanzi: "裤子",
    pinyin: "kù zi",
    hskLevel: 1,
    meaningEn: "Pants",
    meaningMn: "Өмд",
    audioUrl: "/audio/kuzi.mp3",
  },
  {
    id: "xiezi",
    hanzi: "鞋子",
    pinyin: "xié zi",
    hskLevel: 1,
    meaningEn: "Shoes",
    meaningMn: "Гутлын",
    audioUrl: "/audio/xiezi.mp3",
  },
  {
    id: "maozi",
    hanzi: "帽子",
    pinyin: "mào zi",
    hskLevel: 1,
    meaningEn: "Hat",
    meaningMn: "Магад",
    audioUrl: "/audio/maozi.mp3",
  },
  {
    id: "shouji",
    hanzi: "手机",
    pinyin: "shǒu jī",
    hskLevel: 1,
    meaningEn: "Mobile Phone",
    meaningMn: "Гар утас",
    audioUrl: "/audio/shouji.mp3",
  },
  {
    id: "diannao",
    hanzi: "电脑",
    pinyin: "diàn nǎo",
    hskLevel: 1,
    meaningEn: "Computer",
    meaningMn: "Компьютер",
    audioUrl: "/audio/diannao.mp3",
  },
  {
    id: "zhuozi",
    hanzi: "桌子",
    pinyin: "zhuō zi",
    hskLevel: 1,
    meaningEn: "Table",
    meaningMn: "Ширээ",
    audioUrl: "/audio/zhuozi.mp3",
  },
  {
    id: "yizi",
    hanzi: "椅子",
    pinyin: "yǐ zi",
    hskLevel: 1,
    meaningEn: "Chair",
    meaningMn: "Сандал",
    audioUrl: "/audio/yizi.mp3",
  },
  {
    id: "chuang",
    hanzi: "床",
    pinyin: "chuáng",
    hskLevel: 1,
    meaningEn: "Bed",
    meaningMn: "Ор",
    audioUrl: "/audio/chuang.mp3",
  },
  {
    id: "deng",
    hanzi: "灯",
    pinyin: "dēng",
    hskLevel: 1,
    meaningEn: "Light / Lamp",
    meaningMn: "Гэрэл",
    audioUrl: "/audio/deng.mp3",
  },
  {
    id: "men",
    hanzi: "门",
    pinyin: "mén",
    hskLevel: 1,
    meaningEn: "Door",
    meaningMn: "Хаалга",
    audioUrl: "/audio/men.mp3",
  },
  {
    id: "chuanghu",
    hanzi: "窗户",
    pinyin: "chuāng hu",
    hskLevel: 1,
    meaningEn: "Window",
    meaningMn: "Цонх",
    audioUrl: "/audio/chuanghu.mp3",
  },
  {
    id: "che",
    hanzi: "车",
    pinyin: "chē",
    hskLevel: 1,
    meaningEn: "Car / Vehicle",
    meaningMn: "Машин",
    audioUrl: "/audio/che.mp3",
  },
  {
    id: "qiche",
    hanzi: "汽车",
    pinyin: "qì chē",
    hskLevel: 1,
    meaningEn: "Car",
    meaningMn: "Машин",
    audioUrl: "/audio/qiche.mp3",
  },
  {
    id: "zixingche",
    hanzi: "自行车",
    pinyin: "zì xíng chē",
    hskLevel: 1,
    meaningEn: "Bicycle",
    meaningMn: "Унадаг дугуй",
    audioUrl: "/audio/zixingche.mp3",
  },
  {
    id: "feiji",
    hanzi: "飞机",
    pinyin: "fēi jī",
    hskLevel: 1,
    meaningEn: "Airplane",
    meaningMn: "Нисэх онгоц",
    audioUrl: "/audio/feiji.mp3",
  },
  {
    id: "chuan",
    hanzi: "船",
    pinyin: "chuán",
    hskLevel: 2,
    meaningEn: "Boat / Ship",
    meaningMn: "Завь",
    audioUrl: "/audio/chuan.mp3",
  },
  {
    id: "gou",
    hanzi: "狗",
    pinyin: "gǒu",
    hskLevel: 1,
    meaningEn: "Dog",
    meaningMn: "Нохой",
    audioUrl: "/audio/gou.mp3",
  },
  {
    id: "mao",
    hanzi: "猫",
    pinyin: "māo",
    hskLevel: 1,
    meaningEn: "Cat",
    meaningMn: "Муур",
    audioUrl: "/audio/mao.mp3",
  },
  {
    id: "niao",
    hanzi: "鸟",
    pinyin: "niǎo",
    hskLevel: 1,
    meaningEn: "Bird",
    meaningMn: "Шувуу",
    audioUrl: "/audio/niao.mp3",
  },
  {
    id: "ma",
    hanzi: "马",
    pinyin: "mǎ",
    hskLevel: 1,
    meaningEn: "Horse",
    meaningMn: "Морь",
    audioUrl: "/audio/ma.mp3",
  },
  {
    id: "niu",
    hanzi: "牛",
    pinyin: "niú",
    hskLevel: 1,
    meaningEn: "Cow",
    meaningMn: "Үхэр",
    audioUrl: "/audio/niu.mp3",
  },
  {
    id: "yang",
    hanzi: "羊",
    pinyin: "yáng",
    hskLevel: 1,
    meaningEn: "Sheep",
    meaningMn: "Хонь",
    audioUrl: "/audio/yang.mp3",
  },
  {
    id: "ji",
    hanzi: "鸡",
    pinyin: "jī",
    hskLevel: 1,
    meaningEn: "Chicken",
    meaningMn: "Тахиа",
    audioUrl: "/audio/ji.mp3",
  },
  {
    id: "tou",
    hanzi: "头",
    pinyin: "tóu",
    hskLevel: 1,
    meaningEn: "Head",
    meaningMn: "Толгой",
    audioUrl: "/audio/tou.mp3",
  },
  {
    id: "yanjing",
    hanzi: "眼睛",
    pinyin: "yǎn jing",
    hskLevel: 1,
    meaningEn: "Eye",
    meaningMn: "Нүд",
    audioUrl: "/audio/yanjing.mp3",
  },
  {
    id: "bizi",
    hanzi: "鼻子",
    pinyin: "bí zi",
    hskLevel: 1,
    meaningEn: "Nose",
    meaningMn: "Хамар",
    audioUrl: "/audio/bizi.mp3",
  },
  {
    id: "zuiba",
    hanzi: "嘴巴",
    pinyin: "zuǐ ba",
    hskLevel: 1,
    meaningEn: "Mouth",
    meaningMn: "Ам",
    audioUrl: "/audio/zuiba.mp3",
  },
  {
    id: "erduo",
    hanzi: "耳朵",
    pinyin: "ěr duo",
    hskLevel: 1,
    meaningEn: "Ear",
    meaningMn: "Чих",
    audioUrl: "/audio/erduo.mp3",
  },
  {
    id: "shou",
    hanzi: "手",
    pinyin: "shǒu",
    hskLevel: 1,
    meaningEn: "Hand",
    meaningMn: "Гар",
    audioUrl: "/audio/shou.mp3",
  },
  {
    id: "jiao",
    hanzi: "脚",
    pinyin: "jiǎo",
    hskLevel: 1,
    meaningEn: "Foot",
    meaningMn: "Хөл",
    audioUrl: "/audio/jiao.mp3",
  },
  {
    id: "xin",
    hanzi: "心",
    pinyin: "xīn",
    hskLevel: 2,
    meaningEn: "Heart",
    meaningMn: "Зүрх",
    audioUrl: "/audio/xin.mp3",
  },
  {
    id: "hong",
    hanzi: "红",
    pinyin: "hóng",
    hskLevel: 1,
    meaningEn: "Red",
    meaningMn: "Улаан",
    audioUrl: "/audio/hong.mp3",
  },
  {
    id: "huang",
    hanzi: "黄",
    pinyin: "huáng",
    hskLevel: 1,
    meaningEn: "Yellow",
    meaningMn: "Шар",
    audioUrl: "/audio/huang.mp3",
  },
  {
    id: "lan",
    hanzi: "蓝",
    pinyin: "lán",
    hskLevel: 1,
    meaningEn: "Blue",
    meaningMn: "Цэнхэр",
    audioUrl: "/audio/lan.mp3",
  },
  {
    id: "lv",
    hanzi: "绿",
    pinyin: "lǜ",
    hskLevel: 1,
    meaningEn: "Green",
    meaningMn: "Ногоон",
    audioUrl: "/audio/lv.mp3",
  },
  {
    id: "bai",
    hanzi: "白",
    pinyin: "bái",
    hskLevel: 1,
    meaningEn: "White",
    meaningMn: "Цагаан",
    audioUrl: "/audio/bai.mp3",
  },
  {
    id: "hei",
    hanzi: "黑",
    pinyin: "hēi",
    hskLevel: 1,
    meaningEn: "Black",
    meaningMn: "Хар",
    audioUrl: "/audio/hei.mp3",
  },
  {
    id: "chi",
    hanzi: "吃",
    pinyin: "chī",
    hskLevel: 1,
    meaningEn: "To Eat",
    meaningMn: "Идэх",
    audioUrl: "/audio/chi.mp3",
  },
  {
    id: "he",
    hanzi: "喝",
    pinyin: "hē",
    hskLevel: 1,
    meaningEn: "To Drink",
    meaningMn: "Уух",
    audioUrl: "/audio/he.mp3",
  },
  {
    id: "shui-jiao",
    hanzi: "睡",
    pinyin: "shuì",
    hskLevel: 1,
    meaningEn: "To Sleep",
    meaningMn: "Унтах",
    audioUrl: "/audio/shui.mp3",
  },
  {
    id: "qi-lai",
    hanzi: "起",
    pinyin: "qǐ",
    hskLevel: 1,
    meaningEn: "To Get Up",
    meaningMn: "Босох",
    audioUrl: "/audio/qi.mp3",
  },
  {
    id: "zou",
    hanzi: "走",
    pinyin: "zǒu",
    hskLevel: 1,
    meaningEn: "To Walk",
    meaningMn: "Явах",
    audioUrl: "/audio/zou.mp3",
  },
  {
    id: "pao",
    hanzi: "跑",
    pinyin: "pǎo",
    hskLevel: 1,
    meaningEn: "To Run",
    meaningMn: "Гүйх",
    audioUrl: "/audio/pao.mp3",
  },
  {
    id: "kan",
    hanzi: "看",
    pinyin: "kàn",
    hskLevel: 1,
    meaningEn: "To Look / To See",
    meaningMn: "Харах",
    audioUrl: "/audio/kan.mp3",
  },
  {
    id: "ting",
    hanzi: "听",
    pinyin: "tīng",
    hskLevel: 1,
    meaningEn: "To Listen",
    meaningMn: "Сонсох",
    audioUrl: "/audio/ting.mp3",
  },
  {
    id: "shuo",
    hanzi: "说",
    pinyin: "shuō",
    hskLevel: 1,
    meaningEn: "To Speak",
    meaningMn: "Ярих",
    audioUrl: "/audio/shuo.mp3",
  },
  {
    id: "du",
    hanzi: "读",
    pinyin: "dú",
    hskLevel: 1,
    meaningEn: "To Read",
    meaningMn: "Унших",
    audioUrl: "/audio/du.mp3",
  },
  {
    id: "xie",
    hanzi: "写",
    pinyin: "xiě",
    hskLevel: 1,
    meaningEn: "To Write",
    meaningMn: "Бичих",
    audioUrl: "/audio/xie.mp3",
  },
  {
    id: "xuexi",
    hanzi: "学习",
    pinyin: "xué xí",
    hskLevel: 1,
    meaningEn: "To Study / To Learn",
    meaningMn: "Сурч сурах",
    audioUrl: "/audio/xuexi.mp3",
  },
  {
    id: "gongzuo",
    hanzi: "工作",
    pinyin: "gōng zuò",
    hskLevel: 1,
    meaningEn: "To Work / Work",
    meaningMn: "Ажиллах / Ажил",
    audioUrl: "/audio/gongzuo.mp3",
  },
  {
    id: "wan",
    hanzi: "玩",
    pinyin: "wán",
    hskLevel: 1,
    meaningEn: "To Play",
    meaningMn: "Тоглох",
    audioUrl: "/audio/wan.mp3",
  },
  {
    id: "mai",
    hanzi: "买",
    pinyin: "mǎi",
    hskLevel: 1,
    meaningEn: "To Buy",
    meaningMn: "Худалдан авах",
    audioUrl: "/audio/mai.mp3",
  },
  {
    id: "mai2",
    hanzi: "卖",
    pinyin: "mài",
    hskLevel: 1,
    meaningEn: "To Sell",
    meaningMn: "Худалдах",
    audioUrl: "/audio/mai2.mp3",
  },
  {
    id: "lai",
    hanzi: "来",
    pinyin: "lái",
    hskLevel: 1,
    meaningEn: "To Come",
    meaningMn: "Ирэх",
    audioUrl: "/audio/lai.mp3",
  },
  {
    id: "qu",
    hanzi: "去",
    pinyin: "qù",
    hskLevel: 1,
    meaningEn: "To Go",
    meaningMn: "Явах",
    audioUrl: "/audio/qu.mp3",
  },
  {
    id: "hui",
    hanzi: "回",
    pinyin: "huí",
    hskLevel: 1,
    meaningEn: "To Return",
    meaningMn: "Буцах",
    audioUrl: "/audio/hui.mp3",
  },
  {
    id: "zai",
    hanzi: "在",
    pinyin: "zài",
    hskLevel: 1,
    meaningEn: "To Be At / In",
    meaningMn: "Байх",
    audioUrl: "/audio/zai.mp3",
  },
  {
    id: "you",
    hanzi: "有",
    pinyin: "yǒu",
    hskLevel: 1,
    meaningEn: "To Have",
    meaningMn: "Байх",
    audioUrl: "/audio/you.mp3",
  },
  {
    id: "shi",
    hanzi: "是",
    pinyin: "shì",
    hskLevel: 1,
    meaningEn: "To Be",
    meaningMn: "Байх",
    audioUrl: "/audio/shi.mp3",
  },
  {
    id: "hao",
    hanzi: "好",
    pinyin: "hǎo",
    hskLevel: 1,
    meaningEn: "Good",
    meaningMn: "Сайн",
    audioUrl: "/audio/hao.mp3",
  },
  {
    id: "da",
    hanzi: "大",
    pinyin: "dà",
    hskLevel: 1,
    meaningEn: "Big / Large",
    meaningMn: "Том",
    audioUrl: "/audio/da.mp3",
  },
  {
    id: "xiao",
    hanzi: "小",
    pinyin: "xiǎo",
    hskLevel: 1,
    meaningEn: "Small / Little",
    meaningMn: "Жижиг",
    audioUrl: "/audio/xiao.mp3",
  },
  {
    id: "duo",
    hanzi: "多",
    pinyin: "duō",
    hskLevel: 1,
    meaningEn: "Many / Much",
    meaningMn: "Олон",
    audioUrl: "/audio/duo.mp3",
  },
  {
    id: "shao",
    hanzi: "少",
    pinyin: "shǎo",
    hskLevel: 1,
    meaningEn: "Few / Little",
    meaningMn: "Цөөн",
    audioUrl: "/audio/shao.mp3",
  },
  {
    id: "gao",
    hanzi: "高",
    pinyin: "gāo",
    hskLevel: 1,
    meaningEn: "Tall / High",
    meaningMn: "Өндөр",
    audioUrl: "/audio/gao.mp3",
  },
  {
    id: "ai",
    hanzi: "矮",
    pinyin: "ǎi",
    hskLevel: 2,
    meaningEn: "Short (Height)",
    meaningMn: "Бага",
    audioUrl: "/audio/ai.mp3",
  },
  {
    id: "kuai",
    hanzi: "快",
    pinyin: "kuài",
    hskLevel: 1,
    meaningEn: "Fast / Quick",
    meaningMn: "Хурдан",
    audioUrl: "/audio/kuai.mp3",
  },
  {
    id: "man",
    hanzi: "慢",
    pinyin: "màn",
    hskLevel: 1,
    meaningEn: "Slow",
    meaningMn: "Удаан",
    audioUrl: "/audio/man.mp3",
  },
  {
    id: "re",
    hanzi: "热",
    pinyin: "rè",
    hskLevel: 1,
    meaningEn: "Hot",
    meaningMn: "Халуун",
    audioUrl: "/audio/re.mp3",
  },
  {
    id: "leng",
    hanzi: "冷",
    pinyin: "lěng",
    hskLevel: 1,
    meaningEn: "Cold",
    meaningMn: "Хүйтэн",
    audioUrl: "/audio/leng.mp3",
  },
  {
    id: "jin",
    hanzi: "今",
    pinyin: "jīn",
    hskLevel: 1,
    meaningEn: "Today / Now",
    meaningMn: "Өнөөдөр / Одоо",
    audioUrl: "/audio/jin.mp3",
  },
  {
    id: "tian",
    hanzi: "天",
    pinyin: "tiān",
    hskLevel: 1,
    meaningEn: "Day / Sky",
    meaningMn: "Өдөр / Тэнгэр",
    audioUrl: "/audio/tian.mp3",
  },
  {
    id: "nian",
    hanzi: "年",
    pinyin: "nián",
    hskLevel: 1,
    meaningEn: "Year",
    meaningMn: "Жил",
    audioUrl: "/audio/nian.mp3",
  },
  {
    id: "yue",
    hanzi: "月",
    pinyin: "yuè",
    hskLevel: 1,
    meaningEn: "Month / Moon",
    meaningMn: "Сар",
    audioUrl: "/audio/yue.mp3",
  },
  {
    id: "xingqi",
    hanzi: "星期",
    pinyin: "xīng qī",
    hskLevel: 1,
    meaningEn: "Week",
    meaningMn: "Долоо хоног",
    audioUrl: "/audio/xingqi.mp3",
  },
  {
    id: "zuotian",
    hanzi: "昨天",
    pinyin: "zuó tiān",
    hskLevel: 1,
    meaningEn: "Yesterday",
    meaningMn: "Өчигдөр",
    audioUrl: "/audio/zuotian.mp3",
  },
  {
    id: "mingtian",
    hanzi: "明天",
    pinyin: "míng tiān",
    hskLevel: 1,
    meaningEn: "Tomorrow",
    meaningMn: "Маргааш",
    audioUrl: "/audio/mingtian.mp3",
  },
  {
    id: "xianzai",
    hanzi: "现在",
    pinyin: "xiàn zài",
    hskLevel: 1,
    meaningEn: "Now",
    meaningMn: "Одоо",
    audioUrl: "/audio/xianzai.mp3",
  },
  {
    id: "shijian",
    hanzi: "时间",
    pinyin: "shí jiān",
    hskLevel: 1,
    meaningEn: "Time",
    meaningMn: "Цаг",
    audioUrl: "/audio/shijian.mp3",
  },
  {
    id: "dian",
    hanzi: "点",
    pinyin: "diǎn",
    hskLevel: 1,
    meaningEn: "O'clock / Point",
    meaningMn: "Цаг",
    audioUrl: "/audio/dian.mp3",
  },
  {
    id: "fenzhong",
    hanzi: "分钟",
    pinyin: "fēn zhōng",
    hskLevel: 1,
    meaningEn: "Minute",
    meaningMn: "Минут",
    audioUrl: "/audio/fenzhong.mp3",
  },
  {
    id: "xiaoshi",
    hanzi: "小时",
    pinyin: "xiǎo shí",
    hskLevel: 1,
    meaningEn: "Hour",
    meaningMn: "Цаг",
    audioUrl: "/audio/xiaoshi.mp3",
  },
  {
    id: "yi",
    hanzi: "一",
    pinyin: "yī",
    hskLevel: 1,
    meaningEn: "One",
    meaningMn: "Нэг",
    audioUrl: "/audio/yi.mp3",
  },
  {
    id: "er",
    hanzi: "二",
    pinyin: "èr",
    hskLevel: 1,
    meaningEn: "Two",
    meaningMn: "Хоёр",
    audioUrl: "/audio/er.mp3",
  },
  {
    id: "san",
    hanzi: "三",
    pinyin: "sān",
    hskLevel: 1,
    meaningEn: "Three",
    meaningMn: "Гурав",
    audioUrl: "/audio/san.mp3",
  },
  {
    id: "si",
    hanzi: "四",
    pinyin: "sì",
    hskLevel: 1,
    meaningEn: "Four",
    meaningMn: "Дөрөв",
    audioUrl: "/audio/si.mp3",
  },
  {
    id: "wu",
    hanzi: "五",
    pinyin: "wǔ",
    hskLevel: 1,
    meaningEn: "Five",
    meaningMn: "Тав",
    audioUrl: "/audio/wu.mp3",
  },
  {
    id: "liu",
    hanzi: "六",
    pinyin: "liù",
    hskLevel: 1,
    meaningEn: "Six",
    meaningMn: "Зургаа",
    audioUrl: "/audio/liu.mp3",
  },
  {
    id: "qi",
    hanzi: "七",
    pinyin: "qī",
    hskLevel: 1,
    meaningEn: "Seven",
    meaningMn: "Долоо",
    audioUrl: "/audio/qi.mp3",
  },
  {
    id: "ba",
    hanzi: "八",
    pinyin: "bā",
    hskLevel: 1,
    meaningEn: "Eight",
    meaningMn: "Найм",
    audioUrl: "/audio/ba.mp3",
  },
  {
    id: "jiu",
    hanzi: "九",
    pinyin: "jiǔ",
    hskLevel: 1,
    meaningEn: "Nine",
    meaningMn: "Ес",
    audioUrl: "/audio/jiu.mp3",
  },
  {
    id: "shi2",
    hanzi: "十",
    pinyin: "shí",
    hskLevel: 1,
    meaningEn: "Ten",
    meaningMn: "Арав",
    audioUrl: "/audio/shi2.mp3",
  },
]
