export interface Word {
  id: string
  hanzi: string
  pinyin: string
  hskLevel: number
  meaningEn: string
  meaningMn: string
  audioUrl: string
}

export const words: Word[] = [
 // ── Nouns: Places ──────────────────────────────────────────────────────────
  {
    id: "jia",
    hanzi: "家",
    pinyin: "jiā",
    hskLevel: 1,
    meaningEn: "Home",
    meaningMn: "гэр",
    audioUrl: "/audio/nihao.mp3",
  },
  {
    id: "xuexiao",
    hanzi: "学校",
    pinyin: "xuéxiào",
    hskLevel: 1,
    meaningEn: "School",
    meaningMn: "сургууль",
    audioUrl: "/audio/xuexiao.mp3",
  },
  {
    id: "shangdian",
    hanzi: "商店",
    pinyin: "shāngdiàn",
    hskLevel: 1,
    meaningEn: "Store / Shop",
    meaningMn: "дэлгүүр",
    audioUrl: "/audio/shangdian.mp3",
  },
 
  // ── Nouns: People ──────────────────────────────────────────────────────────
  {
    id: "zhongguoren",
    hanzi: "中国人",
    pinyin: "Zhōngguórén",
    hskLevel: 1,
    meaningEn: "Chinese person",
    meaningMn: "хятад хүн",
    audioUrl: "/audio/zhongguoren.mp3",
  },
  {
    id: "baba",
    hanzi: "爸爸",
    pinyin: "bàba",
    hskLevel: 1,
    meaningEn: "Dad",
    meaningMn: "аав",
    audioUrl: "/audio/baba.mp3",
  },
  {
    id: "mama",
    hanzi: "妈妈",
    pinyin: "māma",
    hskLevel: 1,
    meaningEn: "Mom",
    meaningMn: "ээж",
    audioUrl: "/audio/mama.mp3",
  },
  {
    id: "gege",
    hanzi: "哥哥",
    pinyin: "gēge",
    hskLevel: 1,
    meaningEn: "Older brother",
    meaningMn: "ах",
    audioUrl: "/audio/gege.mp3",
  },
  {
    id: "jiejie",
    hanzi: "姐姐",
    pinyin: "jiějie",
    hskLevel: 1,
    meaningEn: "Older sister",
    meaningMn: "эгч",
    audioUrl: "/audio/jiejie.mp3",
  },
  {
    id: "laoshi",
    hanzi: "老师",
    pinyin: "lǎoshī",
    hskLevel: 1,
    meaningEn: "Teacher",
    meaningMn: "багш",
    audioUrl: "/audio/laoshi.mp3",
  },
 
  // ── Nouns: Body ────────────────────────────────────────────────────────────
  {
    id: "erduo",
    hanzi: "耳朵",
    pinyin: "ěrduo",
    hskLevel: 1,
    meaningEn: "Ear",
    meaningMn: "чих",
    audioUrl: "/audio/erduo.mp3",
  },
  {
    id: "yanjing",
    hanzi: "眼睛",
    pinyin: "yǎnjīng",
    hskLevel: 1,
    meaningEn: "Eye",
    meaningMn: "нүд",
    audioUrl: "/audio/yanjing.mp3",
  },
  {
    id: "toufa",
    hanzi: "头发",
    pinyin: "tóufa",
    hskLevel: 1,
    meaningEn: "Hair",
    meaningMn: "үс",
    audioUrl: "/audio/toufa.mp3",
  },
  {
    id: "shou",
    hanzi: "手",
    pinyin: "shǒu",
    hskLevel: 1,
    meaningEn: "Hand",
    meaningMn: "гар",
    audioUrl: "/audio/shou.mp3",
  },
  {
    id: "gezi",
    hanzi: "个子",
    pinyin: "gèzi",
    hskLevel: 1,
    meaningEn: "Height / Stature",
    meaningMn: "өндөр",
    audioUrl: "/audio/gezi.mp3",
  },
  {
    id: "kou",
    hanzi: "口",
    pinyin: "kǒu",
    hskLevel: 1,
    meaningEn: "Mouth",
    meaningMn: "ам",
    audioUrl: "/audio/kou.mp3",
  },
  {
    id: "bizi",
    hanzi: "鼻子",
    pinyin: "bízi",
    hskLevel: 1,
    meaningEn: "Nose",
    meaningMn: "хамар",
    audioUrl: "/audio/bizi.mp3",
  },
 
  // ── Nouns: Animals ─────────────────────────────────────────────────────────
  {
    id: "niao",
    hanzi: "鸟",
    pinyin: "niǎo",
    hskLevel: 1,
    meaningEn: "Bird",
    meaningMn: "шувуу",
    audioUrl: "/audio/niao.mp3",
  },
  {
    id: "mao",
    hanzi: "猫",
    pinyin: "māo",
    hskLevel: 1,
    meaningEn: "Cat",
    meaningMn: "муур",
    audioUrl: "/audio/mao.mp3",
  },
  {
    // Note: PDF shows "够" (OCR error) — correct character is 狗 (dog)
    id: "gou",
    hanzi: "狗",
    pinyin: "gǒu",
    hskLevel: 1,
    meaningEn: "Dog",
    meaningMn: "нохой",
    audioUrl: "/audio/gou.mp3",
  },
  {
    id: "yu",
    hanzi: "鱼",
    pinyin: "yú",
    hskLevel: 1,
    meaningEn: "Fish",
    meaningMn: "загас",
    audioUrl: "/audio/yu.mp3",
  },
 
  // ── Nouns: Food & Drink ────────────────────────────────────────────────────
  {
    id: "pingguo",
    hanzi: "苹果",
    pinyin: "píngguǒ",
    hskLevel: 1,
    meaningEn: "Apple",
    meaningMn: "алим",
    audioUrl: "/audio/pingguo.mp3",
  },
  {
    id: "niunai",
    hanzi: "牛奶",
    pinyin: "niúnǎi",
    hskLevel: 1,
    meaningEn: "Milk",
    meaningMn: "сүү",
    audioUrl: "/audio/niunai.mp3",
  },
  {
    id: "miantiao",
    hanzi: "面条",
    pinyin: "miàntiáo",
    hskLevel: 1,
    meaningEn: "Noodles",
    meaningMn: "гоймон",
    audioUrl: "/audio/miantiao.mp3",
  },
  {
    id: "mifan",
    hanzi: "米饭",
    pinyin: "mǐfàn",
    hskLevel: 1,
    meaningEn: "Rice",
    meaningMn: "будаа",
    audioUrl: "/audio/mifan.mp3",
  },
  {
    id: "shui",
    hanzi: "水",
    pinyin: "shuǐ",
    hskLevel: 1,
    meaningEn: "Water",
    meaningMn: "ус",
    audioUrl: "/audio/shui.mp3",
  },
 
  // ── Nouns: Time ────────────────────────────────────────────────────────────
  {
    id: "dian",
    hanzi: "点",
    pinyin: "diǎn",
    hskLevel: 1,
    meaningEn: "O'clock",
    meaningMn: "цаг",
    audioUrl: "/audio/dian.mp3",
  },
  {
    id: "hao_num",
    hanzi: "号",
    pinyin: "hào",
    hskLevel: 1,
    meaningEn: "Number / Date",
    meaningMn: "дугаар",
    audioUrl: "/audio/hao_num.mp3",
  },
  {
    id: "yue",
    hanzi: "月",
    pinyin: "yuè",
    hskLevel: 1,
    meaningEn: "Month",
    meaningMn: "сар",
    audioUrl: "/audio/yue.mp3",
  },
  {
    id: "xianzai",
    hanzi: "现在",
    pinyin: "xiànzài",
    hskLevel: 1,
    meaningEn: "Now",
    meaningMn: "одоо",
    audioUrl: "/audio/xianzai.mp3",
  },
  {
    id: "jintian",
    hanzi: "今天",
    pinyin: "jīntiān",
    hskLevel: 1,
    meaningEn: "Today",
    meaningMn: "өнөөдөр",
    audioUrl: "/audio/jintian.mp3",
  },
  {
    id: "mingtian",
    hanzi: "明天",
    pinyin: "míngtiān",
    hskLevel: 1,
    meaningEn: "Tomorrow",
    meaningMn: "маргааш",
    audioUrl: "/audio/mingtian.mp3",
  },
  {
    id: "xingqi",
    hanzi: "星期",
    pinyin: "xīngqī",
    hskLevel: 1,
    meaningEn: "Day of the week",
    meaningMn: "гариг",
    audioUrl: "/audio/xingqi.mp3",
  },
 
  // ── Expressions ────────────────────────────────────────────────────────────
  {
    id: "zaijian",
    hanzi: "再见",
    pinyin: "zàijiàn",
    hskLevel: 1,
    meaningEn: "Goodbye",
    meaningMn: "баяртай",
    audioUrl: "/audio/zaijian.mp3",
  },
  {
    id: "xiexie",
    hanzi: "谢谢",
    pinyin: "xièxie",
    hskLevel: 1,
    meaningEn: "Thank you",
    meaningMn: "баярлалаа",
    audioUrl: "/audio/xiexie.mp3",
  },
 
  // ── Verbs ──────────────────────────────────────────────────────────────────
  {
    id: "shi",
    hanzi: "是",
    pinyin: "shì",
    hskLevel: 1,
    meaningEn: "To be",
    meaningMn: "бол",
    audioUrl: "/audio/shi.mp3",
  },
  {
    id: "jiao",
    hanzi: "叫",
    pinyin: "jiào",
    hskLevel: 1,
    meaningEn: "To be called",
    meaningMn: "дуудах",
    audioUrl: "/audio/jiao.mp3",
  },
  {
    id: "he",
    hanzi: "喝",
    pinyin: "hē",
    hskLevel: 1,
    meaningEn: "To drink",
    meaningMn: "уух",
    audioUrl: "/audio/he.mp3",
  },
  {
    id: "chi",
    hanzi: "吃",
    pinyin: "chī",
    hskLevel: 1,
    meaningEn: "To eat",
    meaningMn: "идэх",
    audioUrl: "/audio/chi.mp3",
  },
  {
    id: "qu",
    hanzi: "去",
    pinyin: "qù",
    hskLevel: 1,
    meaningEn: "To go",
    meaningMn: "явах",
    audioUrl: "/audio/qu.mp3",
  },
  {
    id: "you",
    hanzi: "有",
    pinyin: "yǒu",
    hskLevel: 1,
    meaningEn: "To have",
    meaningMn: "байгаа",
    audioUrl: "/audio/you.mp3",
  },
  {
    id: "renshi",
    hanzi: "认识",
    pinyin: "rènshi",
    hskLevel: 1,
    meaningEn: "To know / Recognize",
    meaningMn: "мэдэх",
    audioUrl: "/audio/renshi.mp3",
  },
  {
    id: "xihuan",
    hanzi: "喜欢",
    pinyin: "xǐhuān",
    hskLevel: 1,
    meaningEn: "To like",
    meaningMn: "дуртай",
    audioUrl: "/audio/xihuan.mp3",
  },
  {
    id: "ai",
    hanzi: "爱",
    pinyin: "ài",
    hskLevel: 1,
    meaningEn: "To love",
    meaningMn: "хайртай",
    audioUrl: "/audio/ai.mp3",
  },
  {
    id: "kan",
    hanzi: "看",
    pinyin: "kàn",
    hskLevel: 1,
    meaningEn: "To look / Watch",
    meaningMn: "харах",
    audioUrl: "/audio/kan.mp3",
  },
 
  // ── Adjectives ─────────────────────────────────────────────────────────────
  {
    id: "da",
    hanzi: "大",
    pinyin: "dà",
    hskLevel: 1,
    meaningEn: "Big",
    meaningMn: "том",
    audioUrl: "/audio/da.mp3",
  },
  {
    id: "hao",
    hanzi: "好",
    pinyin: "hǎo",
    hskLevel: 1,
    meaningEn: "Good",
    meaningMn: "сайн",
    audioUrl: "/audio/hao.mp3",
  },
  {
    id: "gaoxing",
    hanzi: "高兴",
    pinyin: "gāoxìng",
    hskLevel: 1,
    meaningEn: "Happy",
    meaningMn: "жаргалтай",
    audioUrl: "/audio/gaoxing.mp3",
  },
  {
    id: "chang",
    hanzi: "长",
    pinyin: "cháng",
    hskLevel: 1,
    meaningEn: "Long",
    meaningMn: "урт",
    audioUrl: "/audio/chang.mp3",
  },
  {
    id: "duo",
    hanzi: "多",
    pinyin: "duō",
    hskLevel: 1,
    meaningEn: "Many / Much",
    meaningMn: "олон",
    audioUrl: "/audio/duo.mp3",
  },
  {
    id: "xiao",
    hanzi: "小",
    pinyin: "xiǎo",
    hskLevel: 1,
    meaningEn: "Small",
    meaningMn: "жижиг",
    audioUrl: "/audio/xiao.mp3",
  },
  {
    id: "gao",
    hanzi: "高",
    pinyin: "gāo",
    hskLevel: 1,
    meaningEn: "Tall / High",
    meaningMn: "өндөр",
    audioUrl: "/audio/gao.mp3",
  },
 
  // ── Pronouns ───────────────────────────────────────────────────────────────
  {
    id: "ta_m",
    hanzi: "他",
    pinyin: "tā",
    hskLevel: 1,
    meaningEn: "He",
    meaningMn: "тэр (эрэгтэй)",
    audioUrl: "/audio/ta_m.mp3",
  },
  {
    id: "wo",
    hanzi: "我",
    pinyin: "wǒ",
    hskLevel: 1,
    meaningEn: "I / Me",
    meaningMn: "би",
    audioUrl: "/audio/wo.mp3",
  },
  {
    id: "ta_f",
    hanzi: "她",
    pinyin: "tā",
    hskLevel: 1,
    meaningEn: "She",
    meaningMn: "тэр (эмэгтэй)",
    audioUrl: "/audio/ta_f.mp3",
  },
  {
    id: "women",
    hanzi: "我们",
    pinyin: "wǒmen",
    hskLevel: 1,
    meaningEn: "We / Us",
    meaningMn: "бид",
    audioUrl: "/audio/women.mp3",
  },
  {
    id: "ni",
    hanzi: "你",
    pinyin: "nǐ",
    hskLevel: 1,
    meaningEn: "You",
    meaningMn: "чи",
    audioUrl: "/audio/ni.mp3",
  },
  {
    id: "zhe",
    hanzi: "这（这儿）",
    pinyin: "zhè (zhèr)",
    hskLevel: 1,
    meaningEn: "This (Here)",
    meaningMn: "энэ (энд)",
    audioUrl: "/audio/zhe.mp3",
  },
  {
    id: "na",
    hanzi: "那（那儿）",
    pinyin: "nà (nàr)",
    hskLevel: 1,
    meaningEn: "That (There)",
    meaningMn: "тэр (тэнд)",
    audioUrl: "/audio/na.mp3",
  },
 
  // ── Question Words ─────────────────────────────────────────────────────────
  {
    id: "ji",
    hanzi: "几",
    pinyin: "jǐ",
    hskLevel: 1,
    meaningEn: "How many",
    meaningMn: "хэдэн",
    audioUrl: "/audio/ji.mp3",
  },
  {
    id: "shenme",
    hanzi: "什么",
    pinyin: "shénme",
    hskLevel: 1,
    meaningEn: "What",
    meaningMn: "ямар",
    audioUrl: "/audio/shenme.mp3",
  },
  {
    id: "na_which",
    hanzi: "哪（哪儿）",
    pinyin: "nǎ (nǎr)",
    hskLevel: 1,
    meaningEn: "Which (Where)",
    meaningMn: "аль",
    audioUrl: "/audio/na_which.mp3",
  },
  {
    id: "shei",
    hanzi: "谁",
    pinyin: "shéi",
    hskLevel: 1,
    meaningEn: "Who",
    meaningMn: "хэн",
    audioUrl: "/audio/shei.mp3",
  },
 
  // ── Numbers ────────────────────────────────────────────────────────────────
  {
    id: "yi",
    hanzi: "一",
    pinyin: "yī",
    hskLevel: 1,
    meaningEn: "One",
    meaningMn: "нэг",
    audioUrl: "/audio/yi.mp3",
  },
  {
    id: "er",
    hanzi: "二",
    pinyin: "èr",
    hskLevel: 1,
    meaningEn: "Two",
    meaningMn: "хоёр",
    audioUrl: "/audio/er.mp3",
  },
  {
    id: "san",
    hanzi: "三",
    pinyin: "sān",
    hskLevel: 1,
    meaningEn: "Three",
    meaningMn: "гурав",
    audioUrl: "/audio/san.mp3",
  },
  {
    id: "si",
    hanzi: "四",
    pinyin: "sì",
    hskLevel: 1,
    meaningEn: "Four",
    meaningMn: "дөрөв",
    audioUrl: "/audio/si.mp3",
  },
  {
    id: "wu",
    hanzi: "五",
    pinyin: "wǔ",
    hskLevel: 1,
    meaningEn: "Five",
    meaningMn: "тав",
    audioUrl: "/audio/wu.mp3",
  },
  {
    id: "liu",
    hanzi: "六",
    pinyin: "liù",
    hskLevel: 1,
    meaningEn: "Six",
    meaningMn: "зургаа",
    audioUrl: "/audio/liu.mp3",
  },
  {
    id: "qi",
    hanzi: "七",
    pinyin: "qī",
    hskLevel: 1,
    meaningEn: "Seven",
    meaningMn: "долоо",
    audioUrl: "/audio/qi.mp3",
  },
  {
    id: "ba",
    hanzi: "八",
    pinyin: "bā",
    hskLevel: 1,
    meaningEn: "Eight",
    meaningMn: "найм",
    audioUrl: "/audio/ba.mp3",
  },
  {
    id: "jiu",
    hanzi: "九",
    pinyin: "jiǔ",
    hskLevel: 1,
    meaningEn: "Nine",
    meaningMn: "ес",
    audioUrl: "/audio/jiu.mp3",
  },
  {
    id: "shi_ten",
    hanzi: "十",
    pinyin: "shí",
    hskLevel: 1,
    meaningEn: "Ten",
    meaningMn: "арав",
    audioUrl: "/audio/shi_ten.mp3",
  },
 
  // ── Measure Words & Particles ──────────────────────────────────────────────
  {
    id: "ge",
    hanzi: "个",
    pinyin: "gè",
    hskLevel: 1,
    meaningEn: "General measure word",
    meaningMn: "бүр",
    audioUrl: "/audio/ge.mp3",
  },
  {
    id: "sui",
    hanzi: "岁",
    pinyin: "suì",
    hskLevel: 1,
    meaningEn: "Years old",
    meaningMn: "нас",
    audioUrl: "/audio/sui.mp3",
  },
 
  // ── Adverbs & Function Words ───────────────────────────────────────────────
  {
    id: "bu",
    hanzi: "不",
    pinyin: "bù",
    hskLevel: 1,
    meaningEn: "No / Not",
    meaningMn: "үгүй",
    audioUrl: "/audio/bu.mp3",
  },
  {
    id: "hen",
    hanzi: "很",
    pinyin: "hěn",
    hskLevel: 1,
    meaningEn: "Very",
    meaningMn: "маш",
    audioUrl: "/audio/hen.mp3",
  },
  {
    id: "he_and",
    hanzi: "和",
    pinyin: "hé",
    hskLevel: 1,
    meaningEn: "And",
    meaningMn: "бас",
    audioUrl: "/audio/he_and.mp3",
  },
  {
    id: "zai",
    hanzi: "在",
    pinyin: "zài",
    hskLevel: 1,
    meaningEn: "At / In / On",
    meaningMn: "д, т",
    audioUrl: "/audio/zai.mp3",
  },
  {
    id: "de",
    hanzi: "的",
    pinyin: "de",
    hskLevel: 1,
    meaningEn: "Possessive particle",
    meaningMn: "ын, ийн",
    audioUrl: "/audio/de.mp3",
  },
  {
    id: "ma",
    hanzi: "吗",
    pinyin: "ma",
    hskLevel: 1,
    meaningEn: "Question particle",
    meaningMn: "уу, үү?",
    audioUrl: "/audio/ma.mp3",
  },
]